{% verbatim %}
<a href='#' {{ action 'toggleCart' }}>View Cart ({{totalItems}})</a>
<div class='cart'>
    <span class='right'>Free Shipping!</span>
    <h1>Your Cart Contents:</h1>
    <hr />
    <form action='https://www.paypal.com/cgi-bin/webscr' method='post'>
        <input type="hidden" name="cmd" value="_cart">
        <input type="hidden" name="upload" value="1">
        <input type="hidden" name="business" value="mahonrig@gmail.com">
        <div class='cartItems'>
            {{#unless totalItems}}
                <h1>Empty Cart</h1>
            {{/unless}}
            {{#each cartItem itemController='cartItem'}}
                <span class='cartItemTitle'>{{title}}</span>
                <span class='cartItemType'>{{type}}</span>
                <span class='cartItemSize'>{{size}}</span>
                <span class='cartItemPrice'>${{price}}</span>
                <button {{action 'removeFromCart' id}}>X</button>
                <input type="hidden"  {{ bind-attr name=paypalFormItem value=paypalFormTitle }}>
                <input type="hidden"  {{bind-attr name=paypalFormAmount value=price }}>
                <br />
            {{/each}}
        </div>
        <hr />
        <span>Total Items: {{totalItems}}</span>
        <span>Total Price: ${{totalPrice}}</span><br />
        {{#if totalItems}}
            <button {{ action 'clearCart' }}>Clear the Cart</button>
            <input class='paypalSubmit' type="submit" value="Pay with PayPal">
        {{/if}}
        <button class='right' {{ action 'hideCart' }}>Hide</button>
    </form>
</div>
{% endverbatim %}