{% verbatim %}
<script type="text/x-handlebars" data-template-name="galleries">
    <section id='galleries'>
    <div class='galleriesMain'>

      {{#each itemController='galleryPreview'}}
          {{#view App.AddPhotoView}}
            <div class="galleryPreview">
            <h1 class='itemTitle'>{{#link-to 'gallery' id}}{{view App.EditTitleView}}{{/link-to}}</h1>
              {{#with id as gallery}}
                {{#view App.DroppablePhotoView}}
                    {{#each photo in photos}}
                        {{#link-to 'photo' gallery photo}}  <img {{bind-attr id='photo.id' src='photo.smallFile' data-gallery='id'}} {{action 'hideGalleries'}}/>{{/link-to}}
                    {{/each}}
                {{/view}}
              {{/with}}
            </div>
          {{/view}}

		   {{/each}}

    </div>
    {{outlet}}
    {{#if admin}}
    {{#view App.RemovePhotoView}}<div class='removePhoto'>Drop here to remove</div>{{/view}}

      <div class='availablePhotos'>
        <div class='showPhotos' {{action 'toggleAllPhotos' target='view'}}><img id='showPhotosIcon' src='/resource/icon-photo.png' alt='Show Photos'/></div>
        <div class='scroll'>
        {{#view App.UploadPhotosView}}
        {{#view App.DroppablePhotoView}}
          <input type='file' id='uploadInput' name='uploadInput' multiple style='display: none'/>
          {{#each photos}}
              <img draggable='true' {{bind-attr src='thumbFile' id='id'}} />
          {{/each}}
        {{/view}}
        {{/view}}
        </div>
    </div>
    {{/if}}
    </section>
</script>

<script type="text/x-handlebars" data-template-name="gallery">
    <div class="galleryView">
        {{outlet}}
        <div class='allPhotos'>
            {{#each photos}}
                <div class='largePhoto'>
                   {{#link-to 'photo' id }}<img {{bind-attr src='largeFile'}} {{action 'hidePhotos'}}/>{{/link-to}}
                    <h2 class='photoTitle'>{{ title }}</h2>
                </div>
            {{/each}}
        </div>
    </div><br />
</script>

<script type="text/x-handlebars" data-template-name="photo">
    <div class='largePhoto'>
       {{#link-to 'gallery' }}<img {{bind-attr src='largeFile'}}/>{{/link-to}}
        <h2 class='photoTitle'>{{ title }}</h2>
    </div>
</script>

<script type="text/x-handlebars" data-template-name="dropPhoto">
  <div class='dropPhoto'>
  <span class='itemTitle'>Drop new Photo here</span>
  </div>
</script>
{% endverbatim %}
