{% verbatim %}
<script type="text/x-handlebars" data-template-name="gallery">
    <section id='gallery'>
        {{outlet photo}}
        {{outlet gallery}}
    </section>
</script>

<script type="text/x-handlebars" data-template-name="gallery/photo">
    <section id='photo'>
        <div class='productLarge'>
            <img {{bind-attr src=largeFile data-id=id}} />
            <h1 class='itemTitle'>{{title}}</h1>
        </div>
    </section>
</script>

<script type="text/x-handlebars" data-template-name="gallery/index">
    <section id='index'>
    <h1 class='itemTitle'>{{ title }}</h1>
        {{#each photos}}
            <div class='productLarge'>
                <img {{bind-attr src=largeFile data-id=id}} />
                <h2 class='itemTitle'>{{ title }}</h2>
            </div>
        {{/each}}
	</section>
</script>
{% endverbatim %}