{% verbatim %}
<script type="text/x-handlebars" data-template-name="galleries">
    <section id='galleries'>
    {{#link-to 'galleries'}}<h1 class='itemTitle'>All Galleries</h1>{{/link-to}}
    <div class='galleriesMain'>
        {{#each itemController='galleryPreview'}}
            <div class="galleryPreview">
           {{#link-to 'gallery' id}} <h1 class='itemTitle' {{action 'hideGalleries'}}>{{title}}</h1>{{/link-to}}
                {{#with id as gallery}}
                    {{#each photo in photos}}
                    <div class='galleryThumb'>
                      {{#link-to 'photo' gallery photo}}  <img {{bind-attr src='photo.thumbFile'}} {{action 'hideGalleries'}}/>{{/link-to}}
                    </div>
                    {{/each}}
                {{/with}}
            </div><br />
		{{/each}}
        
    </div>
    {{outlet}}
    </section>
</script>

<script type="text/x-handlebars" data-template-name="gallery">
    <div class="galleryView">
    {{#link-to 'gallery' id}} <h1 class='itemTitle'>{{title}}</h1>{{/link-to}}
        {{outlet}}
        <div class='allPhotos'>
            {{#each photo in photos}}
                <div class='productLarge'>
                   {{#link-to 'photo' photo.id}} <img {{bind-attr src='photo.largeFile'}} {{action 'hidePhotos'}}/>{{/link-to}}
                </div>
            {{/each}}
        </div>
    </div><br />
</script>

<script type="text/x-handlebars" data-template-name="photo">
    <div class='productLarge'>
       {{#link-to 'gallery' }}<img {{bind-attr src='largeFile'}}/>{{/link-to}}
        <h2 class='itemTitle'>{{ title }}</h2>
    </div>
</script>
{% endverbatim %}