{% verbatim %}
<script type="text/x-handlebars" data-template-name="galleries">
    <section id='galleries'>
    <a href='#' {{ action 'showGalleries'}}>All Galleries</a>
    <div class='galleriesMain'>
        {{#each}}
            <div class="galleryPreview">
                {{#link-to 'gallery' action='slideUp' actionParam=id}}{{title}}{{/link-to}}
                <div class='galleryPreviewThumbs'>
                    {{#each photo in photos}}
                        <img {{bind-attr src='photo.thumbFile'}} />
                    {{/each}}
                </div>
            </div>
		{{/each}}
    </div>
		{{outlet gallery}}
    </section>
</script>
{% endverbatim %}