{% verbatim %}
<script type="text/x-handlebars" data-template-name="admin">
    {{site.title}}
    {{#each galleries}}
    {{title}}
    {{/each}}
    {{#each photos}}
    {{title}}
    {{/each}}
    
    {{view App.NewGalleryView}}

{% endverbatim %}
{{ messages }}

</script>
{% verbatim %}
<script type="text/x-handlebars" data-template-name="addPhotos">
    <div class='drop'>
        <h1>Drop photo's here</h1>
    </div>

</script>

<script type="text/x-handlebars" data-template-name="newPhotoDetails">
        <div class='newPhotoDetails'>
            <h1 class='itemTitle'>Edit details</h1>
            <img class='newPhoto' {{bind-attr src='view.src'}} /><br />
            {{view Ember.TextField value=view.title}}
            <button type='button' {{action 'cancel' target='view'}}>Cancel</button>
            <button type='button' {{action 'submit' target='view'}}>Submit</button><br />
            <progress min='0' max='100' value='0'></progress>
        </div>
</script>

<script type="text/x-handlebars" data-template-name="newGallery">
  <div class='newGallery'>
    <h1 class='itemTitle'>New Gallery: </h1>
    {{view Ember.TextField value=view.title}}
    <button type='button' {{action 'submit' target='view'}}>Submit</button><span class='added'>Added</span><br />
  </div>
</script>
{% endverbatim %}
