{% verbatim %}
<script type="text/x-handlebars">
	<section id='photoworksApp'>
		<header>
{% endverbatim %}
            <h1 id='title'><a href='/'>{{ siteName }}</a></h1>
{% verbatim %}
			<nav id='navBar'>
				<ul>
					<li>{{#link-to 'galleries'}}Galleries{{/link-to}}</li>
					<li><a href='http://mgibsonphotoworks.com/page/about'>About M. Gibson</a></li>
					<li>{{#link-to 'prints'}}Order a Print{{/link-to}}</li>
					<li>
						<a href='#' {{ action 'toggleCart' }}>View Cart ({{totalItems}})</a>
						<div class='cart'>
							<span class='right'>Free Shipping!</span>
							<h1>Your Cart Contents:</h1>
							<hr />
							<form action='https://www.paypal.com/cgi-bin/webscr' method='post'>
								<input type="hidden" name="cmd" value="_cart">
								<input type="hidden" name="upload" value="1">
								<input type="hidden" name="business" value="mahonrig@gmail.com">
								<div class='cartItems'>
									{{#unless totalItems}}
									<h1>Empty Cart</h1>
									{{/unless}}
									{{#each cartItem itemController='cartItem'}}
										<span class='cartItemTitle'>{{title}}</span>
										<span class='cartItemType'>{{type}}</span>
										<span class='cartItemSize'>{{size}}</span>
										<span class='cartItemPrice'>${{price}}</span>
										<button {{action 'removeFromCart' id}}>X</button>
										<input type="hidden"  {{ bind-attr name=paypalFormItem value=paypalFormTitle }}>
										<input type="hidden"  {{bind-attr name=paypalFormAmount value=price }}>
										<br />
									{{/each}}
								</div>
								<hr />
								<span>Total Items: {{totalItems}}</span>
								<span>Total Price: ${{totalPrice}}</span><br />
								{{#if totalItems}}
								<button {{ action 'clearCart' }}>Clear the Cart</button>
								<input class='paypalSubmit' type="submit" value="Pay with PayPal">
								{{/if}}
								<button class='right' {{ action 'hideCart' }}>Hide</button>
							</form>
						</div>
					</li>
				</ul>
			</nav>
		</header>
		<section id='main'>
		{{outlet}}
        </section>
	</section>
</script>
{% endverbatim %}