{% verbatim %}
<script type="text/x-handlebars">
	<section id='photoworksApp'>
		<header>
{% endverbatim %}
            <h1 id='title'><a href='/'>{{ siteName }}</a></h1>
{% verbatim %}
			<nav id='navBar'>
				<ul>
					<li><{{#link-to 'galleries' action='showGalleries'}}Galleries{{/link-to}}</li>
					<li><a href='http://mgibsonphotoworks.com/page/about'>About M. Gibson</a></li>
					<li>{{#link-to 'prints'}}Order a Print{{/link-to}}</li>
					<li>
                        {% endverbatim %}
                        {% include "handlebars/cart.phtml" %}
                        {% verbatim %}
					</li>
				</ul>
			</nav>
		</header>
		<section id='main'>
		{{outlet}}
        </section>
	</section>
</script>
{% endverbatim %}