{% verbatim %}
<script type="text/x-handlebars" data-template-name="order">
    <section id='order'>
        <div class='productLarge'>
            <img {{bind-attr src=url}} />
            <br />
            <h1 class='itemTitle'>{{title}}</h1>
            {{view Ember.Select content=types optionValuePath='content.id'
                optionLabelPath='content.type' value=currentType}}
            {{view Ember.Select classNames='item_size' content=currentOptions optionValuePath='content.id'
                optionLabelPath='content.display' value=currentSize.id prompt="Select Size"}}
            <button {{action 'addToCart' }}>Add to Cart</button>
            <span class='added'>Added!</span>
            <span class='errorSelect'>Please select a size!</span><br />
            {{#link-to 'printDetails' }} More info on print options here! {{/link-to}}
        </div>
    </section>
</script>
{% endverbatim %}