{% verbatim %}
<script type="text/x-handlebars" data-template-name="prints">
    <section id='printsGallery'>
        <div class='products'>
            {{#each itemController='thumb'}}
                <div class='productThumb'>
                    {{#link-to 'order' id}}
                        <img {{bind-attr src=url }} />
                    {{/link-to}}
                </div>
            {{/each}}
        </div>
    </section>
</script>
{% endverbatim %}