{% verbatim %}
<script type="text/x-handlebars" data-template-name="printDetails">
    <section id='printDetails'>
        <h1>Want to know more details about the print options?</h1>
        <hr />
        <h1>Print Only: </h1>
            <h2>High Quality, Beautiful Archival Inkjet Print</h2>
            <p>
                Got a favorite frame shop you like to take your art to?
                Purchase the straight print with no matting or frame, so you customize your wall art.
                Beautiful quality, with ink and printer chosen with careful consideration for optimum results.
            </p>
            <hr />
        <h1>Matted Print:</h1>
            <p>
                Print Comes pre-matted, ready to be inserted into a frame you already own.
                Matted on white non-acidic double weight matt board. Perfect for when you have a
                great frame at home but you want a quality photo ready to put in it.
                The photo comes ready on non-acidic board, so that years from now, your photo
                will still be in top quality.
            </p>
            <hr />
        <h1>Framed Print:</h1>
            <h2>Lovely Dark Wood Frame</h2>
            <p>
                Looking for something ready to hang on the wall?
                Print comes complete, with mat, frame, and a clear acrylic window so you can
                put it directly on your wall or give it as a gift. Beautiful frames and matting
                give a seriousness to the photography that makes people stop and consider it.
                Definitely a focal piece in any room.
            </p>
            <hr />
        <h1>Metal Print:</h1>
            <h2>The Highest Quality Wall-Art</h2>
            <p>
                Comes ready to hang on your wall, with dyes infused directly into a specially coated
                aluminum sheet. Because the image is infused into the surface and not on it, your images
                will take on an almost magical luminescence, adding extra depth to the photography.
                Colors are vibrant and the luminescence is breathtaking. Detail and resolution are unsurpassed.
                This option really gives a clean line and minimalist element that works in almost any setting,
                and really just focuses purely on the photo.
            </p>
    </section>
</script>
{% endverbatim %}