{% verbatim %}
<script type="text/x-handlebars" data-template-name="printDetails">
    <section id='printDetails'>
    <div class='about'>
      <div class='aboutPhoto'>
        <img src='/metal.jpg' />
      </div>
      <div class='mainText'>
        <h1>Archival Print </h1>
            <h2>High Quality, Beautiful Archival Inkjet Print</h2>
            <p>
                Got a favorite frame shop you like to take your art to?
                Purchase the straight print with no matting or frame, so you customize your wall art.
                Beautiful quality, with ink and printer chosen with careful consideration for optimum results.
            </p>
            <hr />
        <h1>Metal Wall Art</h1>
            <h2>The Highest Quality Wall-Art</h2>
            <p>
                Comes ready to hang on your wall, with dyes infused directly into a specially coated
                aluminum sheet. Because the image is infused into the surface and not on it, your images
                will take on an almost magical luminescence, adding extra depth to the photography.
                Colors are vibrant and the luminescence is breathtaking. Detail and resolution are unsurpassed.
                This option really gives a clean line and minimalist element that works in almost any setting,
                and really just focuses purely on the photo.
            </p>
    </section>
</script>
{% endverbatim %}
