
		{% extends 'html.phtml' %}
		{% block Page %}
		{% if messages %}
			<h3 class='warnings'>{{ messages }}</h3>
		{% endif %}
		{% if not admin %}
			<div class='login'>
				<h2>Please Login:</h2>
				<form action='/admin/login' method='post'>
					<label for='username'>Username:</label>
					<input type='text' name='username' size='50' /><br />
					<label for='password'>Password:</label>
					<input type='password' name='password' size='50' /><br />
					<input type='submit' value='Login' /><br />
				</form>
			<div>
		{% else %}
		{% block Content %}
			<div class='admin_galleries'>
				<div class='current'>
				{% if galleries %}				
				<h2>Current Galleries:</h2>
				<ul>
					{% for gallery in galleries %}
					<li>
						<a href='/admin/gallery/{{gallery.id}}'>{{gallery.name}}</a>
						<a href='/admin/remove/gallery/{{gallery.id}}'> | Remove</a>
					</li>
					{% endfor %}
				</ul>
				{% else %}
				<h2>No Galleries yet</h2>
				{% endif %}
				</div>
				<div class='create'>
				<h2>Create a gallery:</h2>
				<form action='/admin/new/gallery' method='POST'>
					<label for='gallery_name'>Gallery Name:</label><br />
					<input type='text' name='gallery_name' /><br />
					<label for='gallery_link'>Link for Gallery (one word)</label><br />
					<input type='text' name='gallery_link' /><br />
					<input type='submit' value='Create Gallery' /><br />
				</form>
				</div>
			</div>
			<div class='admin_photos'>
				<div class='current'>
				{% if photos %}
					<h2>Current Photos:</h2>
					{% for photo in photos %}
						<a href='/admin/photo/{{photo.id}}'><img src='{{photo.thumb_path}}' /></a>
					{% endfor %}
				{% else %}
					<h2>No Photos Yet</h2>
				{% endif %}
				</div>
				<div class='create'>
				<h2>Upload a photo:</h2>
				<form action='/admin/new/photo' method='POST' enctype='multipart/form-data'>
					<label for='photo_file'>File:</label>
					<input type='file' name='photo_file' /><br />
					<label for='photo_name'>Name:</label>
					<input type='text' size='50' name='photo_name' /><br />
					<label for='photo_caption'>Caption(optional):</label><br />
					<textarea name='photo_caption'></textarea><br />
					<input type='submit' value='Upload' />
				</form>
				</div>
				
			</div>
			<div class='admin_pages'>
				<div class='current'>
				{% if pages %}
				<h2>Current Pages:</h2>
				<ul>
					{% for page in pages %}
					<li><a href='/admin/page/{{page.id}}'>{{page.name}}</a></li>
					{% endfor %}
				</ul>
				{% else %}
				<h2>No Pages yet</h2>
				{% endif %}
				</div>
				<div class='create'>
				<h2>Create a new page:</h2>
				<form action='/admin/new/page' method='POST'>
					<label for='page_name'>Page Name:</label>
					<input type='text' name='page_name' /><br />
					<label for='page_link'>Link for Page (one word)</label>
					<input type='text' name='page_link' /><br />
					<textarea id='new_page_content' name='page_content'></textarea><br />
					<input type='submit' value='Create Page' /><br />
				</form>
				</div>
			</div>
			
			<script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
			<script>
				tinymce.init({
					selector:'#new_page_content',
					relative_urls: false,
					remove_script_host: false,
					plugins: [ "image link hr" ],
					toolbar: "undo redo | alignleft aligncenter alignright",
					
					});
				
			</script>
		{% endblock %}
		{% endif %}
		{% endblock %}
