{% extends "admin.phtml" %}

{% block Content %}
<img src='/{{photo.large_path}}' />
<form action='/admin/update/photo/{{photo.id}}' method='POST'>
	<label for='photo_name'>Name:</label>
	<input type='text' name='photo_name' value='{{photo.name}}' /><br />
	<label for='photo_caption'>Caption:</label>
	<textarea id='caption' name='photo_caption'>{{photo.caption}}</textarea>
	<input type='submit' value='Update' /><br />
	{% for gallery in galleries %}
	<input type='checkbox' name='in_gallery[]' value='{{gallery.id}}' {% if gallery.checked %}checked{% endif %}>{{gallery.name}}<br />
	{% endfor %}
	
</form>
<br />
<a href='/admin/remove/photo/{{photo.id}}'>Delete this photo</a>
{% endblock %}