{% extends "admin.phtml" %}

{% block Content %}
<form action='/admin/update/page/{{page.id}}' method='POST'>
	<label for='page_name'>Name:</label>
	<input type='text' name='page_name' value='{{page.name}}' /><br />
	<label for='page_link'>Link (one word): </label>
	<input type='text' name='page_link' value='{{page.link}}' /><br />
	<label for='page_content'>Content:</label><br />
	<textarea id='page_content' name='page_content'>{{ page.content|raw }}</textarea>
	<input type='submit' value='Update Page' />
</form>
<br />
<a href='/admin/remove/page/{{page.id}}'>Remove {{page.name}}</a>

<script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
			<script>
				tinymce.init({
					selector:'#page_content',
					relative_urls: false,
					remove_script_host: false,
					plugins: [ "image link hr" ],
					toolbar: "undo redo | alignleft aligncenter alignright",
					
					});
				
			</script>
{% endblock %}