<!doctype html>
<head>
	<title>{{ pageTitle }}</title>
	<link href='http://fonts.googleapis.com/css?family=Rock+Salt|Varela+Round' rel='stylesheet' type='text/css'>
	<link href='/stylesheets/screen.css' rel='stylesheet' type='text/css'>
</head>
<body>

<script type="text/x-handlebars">
	<section id='photoworksApp'>
		<header>
			<h1 id='title'><a href='/'>{{ siteName }}</a></h1>
			{% verbatim %}
			<nav id='navBar'>
				<ul>
					<li>{{#link-to 'galleries'}}Galleries{{/link-to}}</li>
					<li><a href='http://mgibsonphotoworks.com/page/about'>About M. Gibson</a></li>
					<li>{{#link-to 'prints'}}Order a Print{{/link-to}}</li>
					<li>
						<a href='#' {{ action 'toggleCart' }}>View Cart ({{totalItems}})</a>
						<div class='cart'>
							<span class='right'>Free Shipping!</span>
							<h1>Your Cart Contents:</h1>
							<hr />
							<form action='https://www.paypal.com/cgi-bin/webscr' method='post'>
								<input type="hidden" name="cmd" value="_cart">
								<input type="hidden" name="upload" value="1">
								<input type="hidden" name="business" value="mahonrig@gmail.com">
								<div class='cartItems'>
									{{#unless totalItems}}
									<h1>Empty Cart</h1>
									{{/unless}}
									{{#each cartItem itemController='cartItem'}}
										<span class='cartItemTitle'>{{title}}</span>
										<span class='cartItemType'>{{type}}</span>
										<span class='cartItemSize'>{{size}}</span>
										<span class='cartItemPrice'>${{price}}</span>
										<button {{action 'removeFromCart' id}}>X</button>
										<input type="hidden"  {{ bind-attr name=paypalFormItem value=paypalFormTitle }}>
										<input type="hidden"  {{bind-attr name=paypalFormAmount value=price }}>
										<br />
									{{/each}}
								</div>
								<hr />
								<span>Total Items: {{totalItems}}</span>
								<span>Total Price: ${{totalPrice}}</span><br />
								{{#if totalItems}}
								<button {{ action 'clearCart' }}>Clear the Cart</button>
								<input class='paypalSubmit' type="submit" value="Pay with PayPal">
								{{/if}}
								<button class='right' {{ action 'hideCart' }}>Hide</button>
							</form>
						</div>
					</li>
				</ul>
			</nav>
		</header>
		<section id='main'>
		{{outlet}}
		</section>
</script>
	<script type="text/x-handlebars" data-template-name="galleries">
	<section id='galleries'>
		<p>Gallery Main</p>
		{{#each}}
		{{#link-to 'gallery' id}}{{title}}{{/link-to}}
		{{/each}}
		{{outlet gallery}}
	</section>
	</script>
	<script type="text/x-handlebars" data-template-name="gallery">
	<section id='gallery'>
		<p>In the galleries: {{ title }} </p>
		{{#each photos}}
		<p>{{ title }}</p>
		{{/each}}
	</section>
	</script>
		<script type="text/x-handlebars" data-template-name="prints">
		<section id='printsGallery'>
			<div class='products'>
			{{#each itemController='thumb'}}
				<div class='productThumb'>
					{{#link-to 'order' id}}
						<img {{bind-attr src=url }} />
					{{/link-to}}
				</div>
			{{/each}}
			</div>
		</section>
		</script>
		<script type="text/x-handlebars" data-template-name="order">
		<section id='order'>
			<div class='productLarge'>
						<img {{bind-attr src=url}} />
					<br />
					<h1 class='itemTitle'>{{title}}</h1>
					{{view Ember.Select content=types optionValuePath='content.id'
						 optionLabelPath='content.type' value=currentType}}	
					{{view Ember.Select classNames='item_size' content=currentOptions optionValuePath='content.id'
						 optionLabelPath='content.display' value=currentSize.id prompt="Select Size"}}
					<button {{action 'addToCart' }}>Add to Cart</button><span class='added'>Added!</span><span class='errorSelect'>Please select a size!</span><br />
					{{#link-to 'printDetails' }} More info on print options here! {{/link-to}}
			</div>
		</section>
		</script>
		<script type="text/x-handlebars" data-template-name="printDetails">
		<section id='printDetails'>
			<h1>Want to know more details about the print options?</h1>
			<hr />
			<h1>Print Only: </h1>
				<h2>High Quality, Beautiful Archival Inkjet Print</h2>
				<p>
				 	Got a favorite frame shop you like to take your art to?
				 Purchase the straight print with no matting or frame, so you customize your wall art. 
				 Beautiful quality, with ink and printer chosen with careful consideration for optimum results.
				</p>
			<hr />
			<h1>Matted Print:</h1>
				<p>
					Print Comes pre-matted, ready to be inserted into a frame you already own. 
					Matted on white non-acidic double weight matt board. Perfect for when you have a 
					great frame at home but you want a quality photo ready to put in it. 
					The photo comes ready on non-acidic board, so that years from now, your photo 
					will still be in top quality.
				</p>
			<hr />
			<h1>Framed Print:</h1>
				<h2>Lovely Dark Wood Frame</h2>
				<p>
				Looking for something ready to hang on the wall? 
				Print comes complete, with mat, frame, and a clear acrylic window so you can 
				put it directly on your wall or give it as a gift. Beautiful frames and matting 
				give a seriousness to the photography that makes people stop and consider it. 
				Definitely a focal piece in any room.</p>
			<hr />
			<h1>Metal Print:</h1>
				<h2>The Highest Quality Wall-Art</h2>
				<p>
					Comes ready to hang on your wall, with dyes infused directly into a specially coated
					aluminum sheet. Because the image is infused into the surface and not on it, your images 
					will take on an almost magical luminescence, adding extra depth to the photography.  
					Colors are vibrant and the luminescence is breathtaking. Detail and resolution are unsurpassed. 
					This option really gives a clean line and minimalist element that works in almost any setting, 
					and really just focuses purely on the photo. 
				</p> 
		</section>
		</script>
		{% endverbatim %}	
	</section>
	<script src="/js/libs/jquery-1.10.2.min.js"></script>
  	<script src="/js/libs/handlebars-1.0.0.js"></script>
  	<script src="/js/libs/ember.js"></script>
  	<script src="/js/libs/ember-data.js"></script>
  	<script src="/js/libs/localstorage_adapter.js"></script>
  	<script src="/js/application.js"></script>
</body>
</html>
			