<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>{{ site_name }}</title>
	<!--[if IE]>
      <link href="/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
  	<![endif]-->
	<link href="/stylesheets/style.css" media="screen, projection" rel="stylesheet" type="text/css" />
  	<link href="/stylesheets/print.css" media="print" rel="stylesheet" type="text/css" />
  	<link href='http://fonts.googleapis.com/css?family=Rock+Salt|Varela+Round' rel='stylesheet' type='text/css'>
	
</head>
<body>
	<header>
		<h1 id='banner'><a href='/'>{{ site_name }}</a></h1>
		{% if admin %}
		<ul class='admin_links'>
			<li><a href='/admin'>Admin</a></li>
			<li><a href='/admin/logout'>Logout</a></li>
		</ul>
		{% endif %}
		<nav>
			<ul>
				{% for gallery in galleries %}
				<li><a class='gallery' href='/gallery/{{gallery.link}}'>{{gallery.name}}</a></li>
				{% endfor %}	
			</ul>
			<ul>
				{% for page in pages %}
				<li><a class='page' href='/page/{{page.link}}'>{{page.name}}</a></li>
				{% endfor %}
				<li><a class='page' href='/order'>Order a Print</a></li>
			</ul>
		</nav>	
	</header>
	
	{% block Page %}
	
	{% endblock %}
	
	</body>
</html>