{% extends 'html.phtml' %}

{% block Page %}

	<div class='content'>
	{% if messages %}
	<h3 class='warnings'>{{ messages.warnings }}</h3>
	<h3 class='errors'>{{ messages.errors }} </h3>
	{% endif %}
	{%block Content %}
	<h2>Welcome to the Order page!</h2> 
		<img class='productThumb' src='uploads/thumbs/IMG_0066.jpg' data-name='Dylan' data-ratio='2x3'/>	
		<img class='productThumb' src='uploads/thumbs/IMG_0066.jpg' 
		data-name='Dylan Again' 
		data-ratio='custom'
		data-print='8x10,10x10' 
		data-matt='10x10 on 12x12' 
		data-frame='10x20 in 12x26' 
		data-metal='10x20,12x36'/>	
			
	<br />
	<span class="simpleCart_quantity"></span> items - <span class="simpleCart_total"></span>
	<a href="javascript:;" class="simpleCart_checkout">Checkout</a>
	{% endblock %}
	
	</div>
	
	{% if admin == TRUE %}
	
	{% endif %}
	
	<script src='/js/jquery-1.10.2.js'></script>
	<script src='/js/simpleCart.min.js'></script>
	<script>
	options2x3 = { 
		printOptions: {
			'8x12': 25,
	  	    '12x18': 50,
	 	    '16x24': 75, 
			'20x30': 100
		},
		mattOptions: {
			'8x12 on 11x14': 20, 
	        '11x16 on 16x20': 40, 			  
	        '12x18 on 24x30': 200
	    },
		frameOptions: {
			'8x12 in 11x14': 50, 
			'11x16 in 16x20': 75, 
			'14x20 in 24x30': 200
		},
		metalOptions: {
			'8x12': 33,
	 	    '12x18': 51,
 		    '16x24': 87,
			'20x30': 122
		}
	}
	
	optionsCustom = {
		printOptions: {
			'8x10': 20,
			'10x10': 40,
			'10x20': 50
		},
		mattOptions: {
			'10x10 on 12x12': 20,
			'10x20 on 16x24': 100
		},
		frameOptions: {
			'10x20 in 12x26': 100
		},
		metalOptions: {
			'8x10': 20,
			'10x10': 40,
			'10x20': 50,
			'12x36': 100
		}
	}	
	
	function buildCustomOptions($product)
	{
		printSizes = $product.data('print').split(",");
		mattSizes = $product.data('matt').split(",");
	    frameSizes = $product.data('frame').split(",");
	    metalSizes = $product.data('metal').split(",");
	    print = {};
	    matt = {};
	    frame = {};
	    metal = {};
	    for (var i = 0; i < printSizes.length; i++)
	    {
	    	if (printSizes[i] in optionsCustom.printOptions)
	    	{
	    		print[printSizes[i]] = optionsCustom.printOptions[printSizes[i]];
	    	}
	    }
	    for (var i = 0; i < mattSizes.length; i++)
	    {
	    	if (mattSizes[i] in optionsCustom.mattOptions)
	    	{
	    		matt[mattSizes[i]] = optionsCustom.mattOptions[mattSizes[i]];
	    	}
	    }
	    for (var i = 0; i < frameSizes.length; i++)
	    {
	    	if (frameSizes[i] in optionsCustom.frameOptions)
	    	{
	    		frame[frameSizes[i]] = optionsCustom.frameOptions[frameSizes[i]];
	    	}
	    }
	    for (var i = 0; i < metalSizes.length; i++)
	    {
	    	if (metalSizes[i] in optionsCustom.metalOptions)
	    	{
	    		metal[metalSizes[i]] = optionsCustom.metalOptions[metalSizes[i]];
	    	}
	    }
	    options = { printOptions: print, mattOptions: matt, frameOptions: frame, metalOptions: metal }
	    return options;
	}

	function shelfItem(name, thumb, options)
	{
			this.name = name;
			this.thumb = thumb;
			this.options = 	options;						   
			this.renderThumb = function () {
				$thumbnail = $("<div class='productThumb'><img src='" +
								this.thumb + "' /></div>");
				return $thumbnail;
			}
			this.renderLarge = function () {
				
				$largeView = $(
					"<div class='largeView'>" + 
					"<h2 class='productTitle'>" + this.name + "</h2><br />" + 
					"<img src='" + this.thumb + "' /><br />" +
					"<h3 class='optionTitle'>Print Only:</h3>" + 
					this.renderOptions(this.options.printOptions) +
					"<br /><h3 class='optionTitle'>Matted Prints:</h3>" +
					this.renderOptions(this.options.mattOptions) +
					"<br /><h3 class='optionTitle'>Framed Prints:</h3>" +
					this.renderOptions(this.options.frameOptions) +
					"<br /><h3 class='optionTitle'>Metal Prints:</h3>" +
					this.renderOptions(this.options.metalOptions) +
					"</div>"
				);
				return $largeView;
			}
			this.renderOptions = function (options)
			{
				var printSelect = "<select>";
				for (var option in options)
				{
					printSelect += "<option value='" + option +
								"'>" + option +": $" + options[option] + "</option>";
				}
				printSelect += "</select>";
				return printSelect;	
			}
			
			
			
			
	}
	
	function productView()
	{
		var add_cart_link = "<a class='item_add' href='javascript:;'> Add to Cart </a>";
		
		var end_select = "</select><br />";
		var item_price_span = "<span class='item_price'>";
		
		products = new Array();
		$('.productThumb').each(function(index) {
			if ($(this).data('ratio') == '2x3')
			{
				products[index] = new shelfItem($(this).data('name'), $(this).attr('src'), options2x3);
				$(this).remove();
				$('.content').append(products[index].renderLarge());	
			}
			else if ($(this).data('ratio') == 'custom')
			{
				options = buildCustomOptions($(this));
				products[index] = new shelfItem($(this).data('name'), $(this).attr('src'), options);
				$(this).remove();
				$('.content').append(products[index].renderLarge());
			}
			$(this).append(add_cart_link);
		});
	}
	$(document).ready(function() {
	
		productView();
		
		simpleCart({
			checkout: {
				type: "PayPal",
				email: "mahonrig@gmail.com"
			}
		});
		
		
	});
	</script>

{% endblock %}